baseURL = "https://landvansiem.nl/"
languageCode = "nl-NL"
title = "Het land van Siem"
theme = "crab"
summaryLength = 40

[params]
description = "Trage avonturen in een drassig weiland"
logoimage = "/images/kikker.jpg"
mainSections = ["planten", "dieren", "trivia", "blog"]
copyright = "<a href='https://creativecommons.org/licenses/by/4.0/'>Creative Commons Attribution 4.0 International License.</a>"

[[menu.main]]
weight = 1
name = "Home"
url = "/"

[[menu.main]]
weight = 2
name = "Blog"
url = "/blog/"
identifier = "blog"

[[menu.main]]
weight = 3
name = "Flora"
url = "/planten/"
identifier = "planten"

[[menu.main]]
weight = 4
name = "Fauna"
url = "/dieren/"
identifier = "dieren"

#  [[menu.main]]
#  parent = "planten"
#  weight = 1
#  name = "Waterkers"
#  url = "/planten/waterkers/"
#
#  [[menu.main]]
#  parent = "planten"
#  weight = 2
#  name = "Watermunt"
#  url = "/planten/watermunt/"

[[menu.main]]
weight = 5
name = "Trivia"
url = "/trivia/"
identifier = "trivia"

[[menu.main]]
weight = 6
name = "Knipsels & links"
url = "/knipsels/"
identifier = "knipsels"
